# Load packages ----
library(bsplus)  # bs_accordion()
library(data.table)
# require digest 0.6.23 as we experience issues with subsequent versions
library(digest)
library(DT)
library(flexdashboard)  # gaugeOutput()
library(flextable)
library(foreign)
library(grid)  # textGrob()
library(gridExtra)
library(highcharter)  # highchartOutput()
library(knitr)
library(jsonlite)  # toJSON()
library(lubridate)  # floor_date()
library(markdown)
library(openssl)
library(pushbar)  # pushbar_deps()
library(RColorBrewer)
library(readxl)
library(shiny)
library(shinyBS)
library(shinyhelper)  # helper()
library(shinythemes)  # shinytheme()
library(shinyWidgets)  # switchInput()
library(tidyverse)  # App requires recent version for the implementation of na.rm in unite()
library(tools)  # file_ext()
library(timevis)  # timevisOutput()
library(vov)  # swivel_vertical()


cols_sir <- c("#2166ac", "#fddbc7", "#b2182b")  # resp. S, I, R