---
title: "ACORN AMR Report"
output: word_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

patient <- patient()
```

Report generated the `r Sys.time()`.

# Profile of Patients

## Total Number of Patients 

### Per Surveillance Category

Ward Type:
```{r}
# ward type
patient %>%
  group_by(ward, surveillance_cat) %>%
  summarise(patients = n()) %>%
  ungroup() %>%
  complete(surveillance_cat, ward) %>%
  mutate(patients = replace_na(patients, 0)) %>%
  pivot_wider(names_from = surveillance_cat, values_from = patients) %>%
  kable(format = "markdown", col.names = c("Type of Ward", "CAI", "HAI"), 
        padding = 2, align = "rcc")
```

</br>
Age Category:

```{r size=16}
# age category
patient %>%
  mutate(age_category = case_when(
    age < 1 ~ "Less than 1",
    age < 5 ~ "1 to  5",
    TRUE ~ "Above 5")) %>%
  mutate(age_category = factor(age_category, levels = c("Less than 1", "1 to  5", "Above 5"))) %>% 
  group_by(age_category, surveillance_cat) %>%
  summarise(patients = n()) %>%
  ungroup() %>%
  complete(surveillance_cat, age_category) %>%
  mutate(patients = replace_na(patients, 0)) %>%
  pivot_wider(names_from = surveillance_cat, values_from = patients) %>%
  kable(format = "markdown", col.names = c("Age Category", "CAI", "HAI"))
```

TODO: Add Diagnosis Suspected, Outcome, Day 28 status.

### Per Diagnosis

Ward Type:
```{r}
# ward type
patient %>%
  group_by(ward, surveillance_diag) %>%
  summarise(patients = n()) %>%
  ungroup() %>%
  complete(surveillance_diag, ward) %>%
  mutate(patients = replace_na(patients, 0)) %>%
  pivot_wider(names_from = surveillance_diag, values_from = patients) %>%
  kable(format = "markdown", padding = 2)
```